## Linear Regression
An estimator is any model that tries to estimate a variable y from another variable(s) x given pairs of data (x<sub>1</sub>,y<sub>1</sub>),(x<sub>2</sub>,y<sub>2</sub>),...,(x<sub>N</sub>,y<sub>N</sub>)

Regression is when the targets (y) are quantities (not cat vs dog but rather price of a house)

An example would be trying to guess how many people will buy icecream from a shop at any day given the temprature on that day. In this case, the target is the number of icecream people will buy, it is an integer and any value (ex: 14 icecreams) doesn't represent a particular class, so it will be represented as a regression problem. In this case, it turns out that x is also a quantity (temprature); however, this is not necessary and is tackled by approaches other than linear regression.

To estimate the price of the icecream from temperature we gather the data on various days from various different places and get the following data.



We can see that a line (could  also be a curve) could fit the data, but how can we find which line exactly.

#### Line Equation Review
A line in 2D can be parametrized using a slope m and a y-intercept b which would result in it having an equation

$$y = mx+b$$

In the example of the icecream, if the temperature at a day was 30, our prediction for the number of icecreams sold would be m\*30 + b, so we simply need to find m and b.

#### Squared Loss
We need some measurement of how good our line is to be able to find the "best" line, so we will measure the difference between our predictions and the correct values from the data.


Then, we will square all the differences and add them up. This will be the value we try to minimize.

#### Note
The normal equation will probably not work. It is left for you to figure it out and let everyone else know, let's see who figures it out first (it's a tricky issue).




In [1]:
import numpy as np
import pandas as pd

In [64]:
class Linear_Regression():

    '''
    Linear Regression model created using only NumPy
    
    Attributes
    ----------
    weights: np.array of floats
        All the parameters of the model (including bias)
    '''
    def __init__(self):
        self.weights = None
        
    def train(self,data_X,data_y):

        x=np.linalg.pinv(data_X)
        W= new.dot(data_y)
        self.weights=W
     
        '''
        Train the model using the given data
        
        Parameters
        ----------
        data_X: np.array, shape = (N, num_features)
            Features from the data, each row is one data point. Assumes that a column of ones was added to data_X
        data_y: np.array, shape = (N, num_targets)
            The target values to predict, each row contains the targets for one data point
        '''
        ########################## Insert code here ##########################

    def predict(self,x_to_predict):
     
        ypredict=x_to_predict.dot(self.weights)
        return ypredict
        '''
        Predict using the given value as input
        
        Assumes that self.train(.,.) has been called before calling this method
        
        Parameters
        ----------
        x_to_predict: np.array, shape = (M, num_features)
            A given list of inputs to predict targets for, each row is one input. Assumes that a column of ones was added similar to the training data
        
        Returns
        -------
        np.array of floats, shape = (M, num_targets)
            Predicted values for each input
        '''
        ########################## Insert code here ##########################

### Import the data and remove useless columns

In [3]:

df = pd.read_csv("train.csv")
df.drop(columns=["Id"],inplace=True)
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          60       RL         65.0     8450   Pave   NaN      Reg   
1          20       RL         80.0     9600   Pave   NaN      Reg   
2          60       RL         68.0    11250   Pave   NaN      IR1   
3          70       RL         60.0     9550   Pave   NaN      IR1   
4          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
0         Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
1         Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
2         Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
3         Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
4         Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

### Handle the missing data (NaNs)

In [4]:
df.drop(columns=df.columns[df.isnull().sum().values>200],inplace=True)
df.dropna(inplace=True)
df.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### Replace categorical data (strings) with numerical values

In [5]:
obj_to_replace = df["MSZoning"].dtype

for column in df.columns:
    if df[column].dtype == obj_to_replace:
        uniques = np.unique(df[column].values)
        for idx,item in enumerate(uniques):
            df[column] = df[column].replace(item,idx)
            
df.head()

MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  \
0          60         3     8450       1         3            3          0   
1          20         3     9600       1         3            3          0   
2          60         3    11250       1         0            3          0   
3          70         3     9550       1         0            3          0   
4          60         3    14260       1         0            3          0   

   LotConfig  LandSlope  Neighborhood  ...  EnclosedPorch  3SsnPorch  \
0          4          0             5  ...              0          0   
1          2          0            24  ...              0          0   
2          4          0             5  ...              0          0   
3          0          0             6  ...            272          0   
4          2          0            15  ...              0          0   

   ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0            0         0        0       2    2008         8              4   
1            0         0        0       5    2007         8              4   
2            0         0        0       9    2008         8              4   
3            0         0        0       2    2006         8              0   
4            0         0        0      12    2008         8              4   

   SalePrice  
0     208500  
1     181500  
2     223500  
3     140000  
4     250000  

[5 rows x 74 columns]

### Add the bias column (column of ones)

In [6]:
df["bias"] = np.ones(df.shape[0])
df.head()

MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  \
0          60         3     8450       1         3            3          0   
1          20         3     9600       1         3            3          0   
2          60         3    11250       1         0            3          0   
3          70         3     9550       1         0            3          0   
4          60         3    14260       1         0            3          0   

   LotConfig  LandSlope  Neighborhood  ...  3SsnPorch  ScreenPorch  PoolArea  \
0          4          0             5  ...          0            0         0   
1          2          0            24  ...          0            0         0   
2          4          0             5  ...          0            0         0   
3          0          0             6  ...          0            0         0   
4          2          0            15  ...          0            0         0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  bias  
0        0       2    2008         8              4     208500   1.0  
1        0       5    2007         8              4     181500   1.0  
2        0       9    2008         8              4     223500   1.0  
3        0       2    2006         8              0     140000   1.0  
4        0      12    2008         8              4     250000   1.0  

[5 rows x 75 columns]

### Divide the data into training, testing, X, and y

In [17]:
df = df.sample(frac=1).reset_index(drop=True)
training_df = df[:-100]
val_df = df[-100:]
training_y = training_df["SalePrice"].values
training_X = training_df.drop(columns=["SalePrice"]).values

test_y = val_df["SalePrice"].values
test_X = val_df.drop(columns=["SalePrice"]).values

print(training_X.shape)
print(np.mean(training_y))

(1238, 74)
187667.22778675283


array([[1.9000e+02, 4.0000e+00, 1.0120e+04, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [2.0000e+01, 3.0000e+00, 9.8580e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [2.0000e+01, 3.0000e+00, 8.5210e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       ...,
       [2.0000e+01, 3.0000e+00, 8.5930e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [6.0000e+01, 3.0000e+00, 1.4598e+04, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [1.6000e+02, 4.0000e+00, 1.6800e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00]])

### Train the linear regressor

In [61]:
# Create and fit the model
LR_regressor = Linear_Regression()
LR_regressor.train(training_X,training_y)
# Calculate Mean Absolute Error (Easier to interpret than MSE)

ypredict=LR_regressor.predict(test_X)
MAE_lr= np.absolute(ypredict-test_y)
print (MAE_lr)


########################## Insert code here ##########################

[7.14981886e+03 6.45107852e+03 2.10197967e+03 2.04590439e+04
 5.14005560e+04 3.10195284e+04 1.46550907e+04 4.82199084e+04
 4.98801177e+04 6.17228224e+03 1.11044370e+04 1.62357175e+04
 8.97462637e+04 4.57073200e+03 2.33435242e+04 1.28522313e+04
 4.70105942e+04 3.67737770e+04 9.36489175e+03 3.51721132e+03
 2.82335461e+03 2.74686932e+03 6.53220836e+03 1.96910180e+02
 9.50406836e+02 1.80629249e+04 2.60670011e+04 2.17838845e+04
 7.39973670e+03 8.38634558e+04 2.35440108e+04 1.32843246e+03
 3.50831003e+03 1.54030852e+03 4.02373869e+03 1.12958044e+04
 2.06038444e+04 9.82669224e+03 1.19088292e+04 7.57768211e+03
 3.78657770e+03 5.42679531e+03 4.85400611e+03 5.03057004e+04
 2.21696052e+04 9.12768384e+02 2.58441167e+04 2.56991013e+04
 4.64989266e+03 2.25633321e+04 2.34227763e+04 7.35269851e+03
 1.92570249e+04 1.06494320e+03 9.59955374e+03 1.59369285e+04
 1.69323333e+04 2.28006342e+04 1.12602720e+04 1.66265022e+04
 4.09636972e+03 1.37302262e+04 9.53342910e+02 2.21624660e+04
 1.21938178e+04 1.533859

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0], dtype=int64)

MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  \
0          20         2    11622       1         3            3          0   
1          20         3    14267       1         0            3          0   
2          60         3    13830       1         0            3          0   
3          60         3     9978       1         0            3          0   
4         120         3     5005       1         0            1          0   

   LotConfig  LandSlope  Neighborhood  ...  OpenPorchSF  EnclosedPorch  \
0          4          0            12  ...            0              0   
1          0          0            12  ...           36              0   
2          4          0             8  ...           34              0   
3          4          0             8  ...           36              0   
4          4          0            22  ...           82              0   

   3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0          0          120         0        0       6    2010         8   
1          0            0         0    12500       6    2010         8   
2          0            0         0        0       3    2010         8   
3          0            0         0        0       6    2010         8   
4          0          144         0        0       1    2010         8   

   SaleCondition  
0              4  
1              4  
2              4  
3              4  
4              4  

[5 rows x 73 columns]

MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  \
0          20         2    11622       1         3            3          0   
1          20         3    14267       1         0            3          0   
2          60         3    13830       1         0            3          0   
3          60         3     9978       1         0            3          0   
4         120         3     5005       1         0            1          0   

   LotConfig  LandSlope  Neighborhood  ...  EnclosedPorch  3SsnPorch  \
0          4          0            12  ...              0          0   
1          0          0            12  ...              0          0   
2          4          0             8  ...              0          0   
3          4          0             8  ...              0          0   
4          4          0            22  ...              0          0   

   ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0          120         0        0       6    2010         8              4   
1            0         0    12500       6    2010         8              4   
2            0         0        0       3    2010         8              4   
3            0         0        0       6    2010         8              4   
4          144         0        0       1    2010         8              4   

   bias  
0   1.0  
1   1.0  
2   1.0  
3   1.0  
4   1.0  

[5 rows x 74 columns]

(1219, 74)

array([[8.0000e+01, 3.0000e+00, 1.0200e+04, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [1.2000e+02, 3.0000e+00, 5.9110e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [5.0000e+01, 3.0000e+00, 6.1910e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       ...,
       [6.0000e+01, 3.0000e+00, 1.1002e+04, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [1.2000e+02, 4.0000e+00, 3.9070e+03, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00],
       [6.0000e+01, 3.0000e+00, 1.1800e+04, ..., 8.0000e+00, 4.0000e+00,
        1.0000e+00]])

(1219, 74)


MSSubClass  MSZoning  LotArea  Street  LotShape  LandContour  Utilities  \
0             20         1     8640       1         3            3          0   
1             45         4     6120       1         3            3          0   
2             20         3     5175       1         3            3          0   
3             20         3     8760       1         3            3          0   
4            120         4     2394       1         3            2          0   
...          ...       ...      ...     ...       ...          ...        ...   
1214          70         4     4800       1         3            3          0   
1215          20         1     8640       1         3            3          0   
1216          50         4     6000       1         3            3          0   
1217          20         3    13008       1         0            3          0   
1218          50         3     8382       1         3            3          0   

      LotConfig  LandSlope  Neighborhood  ...  EnclosedPorch  3SsnPorch  \
0             4          0            21  ...              0          0   
1             4          0             3  ...            136          0   
2             4          0             3  ...              0          0   
3             4          0            12  ...              0          0   
4             4          1            10  ...             56          0   
...         ...        ...           ...  ...            ...        ...   
1214          4          0            17  ...              0          0   
1215          4          0            21  ...              0          0   
1216          4          0             3  ...              0          0   
1217          4          0            12  ...              0          0   
1218          4          0            12  ...              0          0   

      ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0               0         0        0      10    2006         6              5   
1               0         0        0       7    2007         8              4   
2               0         0        0       7    2007         0              4   
3               0         0        0       6    2009         8              4   
4             108         0        0       5    2010         8              4   
...           ...       ...      ...     ...     ...       ...            ...   
1214            0         0        0       1    2008         8              4   
1215            0         0        0       5    2009         8              4   
1216            0         0        0       3    2010         8              4   
1217            0         0        0      10    2009         8              4   
1218            0         0        0       2    2010         8              4   

      bias  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0  
...    ...  
1214   1.0  
1215   1.0  
1216   1.0  
1217   1.0  
1218   1.0  

[1219 rows x 74 columns]

### Train using the sklearn linear regressor

In [60]:
from sklearn.linear_model import LinearRegression

sk_regressor = LinearRegression()

sk_regressor.fit(training_X, training_y)

ypred = sk_regressor.predict(test_X)

# Create and fit the model
########################## Insert code here ##########################

# Calculate Mean Absolute Error (Easier to interpret than MSE)
MAE_sk= np.absolute(ypred-test_y)
print(MAE_sk)
########################## Insert code here ##########################

[7.14981886e+03 6.45107852e+03 2.10197967e+03 2.04590439e+04
 5.14005560e+04 3.10195284e+04 1.46550907e+04 4.82199084e+04
 4.98801177e+04 6.17228224e+03 1.11044370e+04 1.62357175e+04
 8.97462637e+04 4.57073200e+03 2.33435242e+04 1.28522313e+04
 4.70105942e+04 3.67737770e+04 9.36489175e+03 3.51721132e+03
 2.82335461e+03 2.74686932e+03 6.53220836e+03 1.96910180e+02
 9.50406836e+02 1.80629249e+04 2.60670011e+04 2.17838845e+04
 7.39973670e+03 8.38634558e+04 2.35440108e+04 1.32843246e+03
 3.50831003e+03 1.54030852e+03 4.02373869e+03 1.12958044e+04
 2.06038444e+04 9.82669224e+03 1.19088292e+04 7.57768211e+03
 3.78657770e+03 5.42679531e+03 4.85400611e+03 5.03057004e+04
 2.21696052e+04 9.12768384e+02 2.58441167e+04 2.56991013e+04
 4.64989266e+03 2.25633321e+04 2.34227763e+04 7.35269851e+03
 1.92570249e+04 1.06494320e+03 9.59955374e+03 1.59369285e+04
 1.69323333e+04 2.28006342e+04 1.12602720e+04 1.66265022e+04
 4.09636972e+03 1.37302262e+04 9.53342910e+02 2.21624660e+04
 1.21938178e+04 1.533859